#define DYNAMIC_KEYMAP_LAYER_COUNT 10
#define LAYER_STATE_32BIT
#define SERIAL_USART_TX_PIN GP14
#define SERIAL_PIO_USE_PIO0
#define PS2_PIO_USE_PIO1
#undef SPLIT_USB_DETECT
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_USB_TIMEOUT 5000
#define SPLIT_POINTING_ENABLE