#define LAYER_STATE_32BIT
#define DYNAMIC_KEYMAP_LAYER_COUNT 15
#undef SPLIT_USB_DETECT
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_POINTING_ENABLE
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_MAX_CONNECTION_ERRORS 10
#define PS2_MOUSE_USE_REMOTE_MODE
#define SERIAL_PIO_USE_PIO1
#define PS2_PIO_USE_PIO0
#define PS2_MOUSE_SCROLL_BTN_MASK 0
#define PS2_MOUSE_ROTATE 90
#define PS2_MOUSE_USE_REMOTE_MODE
// RC回路でハードウェアリセット済みなので待機を短縮
#define PS2_MOUSE_INIT_DELAY 100
#define PS2_MOUSE_SAMPLE_RATE 100
// PS/2からは生の値を取得(後でフックで調整)
#define PS2_MOUSE_X_MULTIPLIER 1
#define PS2_MOUSE_Y_MULTIPLIER 1
#define PS2_MOUSE_V_MULTIPLIER 1

// Unicode入力設定: Linux用の確定キーをEnterに変更
#define UNICODE_KEY_LINUX KC_ENT